server:
  port: '7000'

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jwt_mastery?useSSL=false
    username: shazzar
    password: Las-jefa5
  jpa:
    hibernate:
      ddl-auto: update

